Added quickslice
ufo-kit/nova-thumbnail-server pull request #1
Opened 2018-05-29 17:15 UTC by raghavaro

Added quickslice for thumbnails in wave zoom preview

2018-05-30 07:16 UTC, matze requested changes

2018-05-30 07:16 UTC, matze commented on run.py
> +from quickslice.slice import slice
Don't pull `slice` into the global namespace, it is a reserved Python keyword. Just import `quickslice` and access the names `build` and `slice` using the dot.

2018-06-01 14:53 UTC, raghavaro commented
how about now?

2018-06-05 12:56 UTC, matze commented
I am not super convinced that the way it is now is good. You process a lot of data in the same process where the request is made. This won't scale because you block the entire server process. You should implement it in the same way as the `nova-wave-server` by spawning a new process and some protocol which communicates with the frontend to notify when processing is done.

2018-06-05 14:42 UTC, raghavaro commented
Yes you are right. It will not scale. I can do it like the wave-server. I’ll get it done and send a PR. 

Best regards,
Raghav Arora

> On 5. Jun 2018, at 14:56, Matthias Vogelgesang <notifications@github.com> wrote:
> 
> I am not super convinced that the way it is now is good. You process a lot of data in the same process where the request is made. This won't scale because you block the entire server process. You should implement it in the same way as the nova-wave-server by spawning a new process and some protocol which communicates with the frontend to notify when processing is done.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2018-08-25 17:44 UTC, closed without merging